### ISSUE TITLE
File list updates failing after multiple scoped requests

### ISSUE THREAD

**Issue by harunsmrkovic** [digime/digime-sdk-ios#162]
## Checklist
- [x] I’m using the latest version of the digi.me Private Sharing SDK.
- [x] I'm using the latest version of the digi.me App.
- [x] I've searched for existing [GitHub issues](https://github.com/digime/digime-sdk-ios/issues)
- [x] I've looked for existing answers in the [SDK Documentation](https://digime.github.io/digime-sdk-ios/index.html) and [Developer FAQs](https://digime.freshdesk.com/support/solutions/9000115894) 
- [x] This issue does not relate to security and can be disclosed publicly on Github. 
## Environment
Describe your development environment here. Please provide as much information as you can, noting the following details if possible:
- Xcode Version: `X.X.X`
- Swift Version: `X.X.X` (if applicable)
- Installation Platform & Version: `[Cocoapods]` version `3.1.0`
## Goals
What are you trying to achieve? 
Do fileList polls throughout multiple scoped requests
## Expected Results
What do you expect to happen?
Getting poll updates from every request
## Actual Results
What actually happened?
Account updates failing due to invalid session, in second or third request (not always same)
## Steps to Reproduce
What are the steps necessary to reproduce this issue?
1. Authorize 1 scope
2. Poll for fileList updates
3. Wait until they are all completed/partial/timed-out
4. Authorize 2nd (different) scope
5. Poll for fileList updates
6. Repeat until you get `invalid session` error for fileList update call
## Code Samples & Details

```
[digime] Authorize (with scope) inited
NativeBridge.js:29 Removing listener fileListUpdate
index.js:61 [digi.me] Authorization successful {"sessionKey":"KkaaitcmudPxq3g3BAKh5DJB4tCiYTRP"}
index.js:136 Subscribing to Account Sync Updates
NativeBridge.js:20 Adding listener fileListUpdate
index.js:141 [digi.me] Initiated getFileList via SDK
index.js:70 [digi.me] Initiated getAccounts via SDK
RCTLog.js:47 [digime] Get Accounts inited
index.js:74 [digime] Got Accounts [{"id":"...","name":"...","service":{"name":"Twitter","logo":"https:\/\/securedownloads.digi.me\/static\/production\/discovery\/services\/twitter\/icon75x75.png"}}]
RCTLog.js:47 [digime] getSessionFileList Failed: Invalid session.
index.js:149 [digi.me] Get File List failed Error: Invalid session.
NativeBridge.js:29 Removing listener fileListUpdate

```

**Comment by BeckFW** [comment]
Harun, are you still able to reproduce this issue? You mentioned some time ago that it was causing issues with your iOS release, so it would be good to know if that is still the case. 

It's possible that this is caused by the session expiring or a contract issue, so we will investigate further if it is still affecting you. If you are able to reproduce it, please could you attach some logs containing timestamps to aid in identifying when the error occurs. 

Let me know. :)

**Comment by harunsmrkovic** [comment]
> Harun, are you still able to reproduce this issue? You mentioned some time ago that it was causing issues with your iOS release, so it would be good to know if that is still the case.
> 
> It's possible that this is caused by the session expiring or a contract issue, so we will investigate further if it is still affecting you. If you are able to reproduce it, please could you attach some logs containing timestamps to aid in identifying when the error occurs.
> 
> Let me know. :)

Has anything been done to address this issue? If not, I doubt that anything has changed from since I've reported the issue. There is also a `sessionKey` attached above for the affected session.

I don't have resources at the moment to re-test this as thorough, but will report if it re-occurs.

**Comment by harunsmrkovic** [comment]
I've just had a similar thing happen, although it did not fail, but instead said it completed, but without streaming any data.

I did 5-6 authorizations and `getSessionData` calls, and then I did one more, and I got this:

`
2020-02-12 12:06:57.588573+0700 mobileUbdiApp[5822:3956962] Instabug - REACT LOG: 2020-02-12 12:06:57.588 [info][tid:com.facebook.react.JavaScript] '[digi.me] Authorization successful', '{"sessionKey":"HerPUB3WFcpMU7f2PRYGN4bYBYNR3AU2"}'
`
`
2020-02-12 12:06:57.589396+0700 mobileUbdiApp[5822:3954761] DigiMeSDK: Refreshing file list
`
`
2020-02-12 12:06:59.325858+0700 mobileUbdiApp[5822:3956961] [DMEAPIClient] Queued downloads completed.
`
```
2020-02-12 12:06:59.325858+0700 mobileUbdiApp[5822:3956961] [DMEAPIClient] Queued downloads completed.
2020-02-12 12:06:59.325988+0700 mobileUbdiApp[5822:3956961] DigiMeSDK: Finished Downloading all files
2020-02-12 12:06:59.326090+0700 mobileUbdiApp[5822:3956961] DigiMeSDK: Sync state - partial
2020-02-12 12:06:59.326178+0700 mobileUbdiApp[5822:3956961] DigiMeSDK: Finished fetching session data.
```
`
2020-02-12 12:07:00.003056+0700 mobileUbdiApp[5822:3953721] DigiMeSDK: Found new files to sync: 6
`

and after this it resolved the (success) completion block.

**Comment by brokenzz** [comment]
Sounds like there might be a bug where if the first SDK `fileList` fetch returns an already completed fileList (in `partial` or `completed` state), then files aren’t downloaded, and instead `completion` is called, **or** completion is called prematurely. Needs investigation

**Comment by brokenzz** [comment]
So I've done some digging around, and I wasn't actually able to reproduce the updated issue you reported. I tested my theory above about SDK not behaving as expected if it receives FileList for the first time in already `completed` state - but it works as expected. I triggerred subsequent scope requests while current was still executing, but again - had no problems.

It then hit me - in our recent chat I mentioned to you that whenever you are doing new `authorize` type request, you should also start with a brand new instance of `DMEPullClient`. Which is what I was doing in my tests.

To see if I'd get any issues otherwise I tried re-using the same instance for all `authorize` requests, while fetching is taking place to see what happens - and guess what - I was able to reproduce your original issue:
```
Failed to retrieve content for fileId: <…> Error: Invalid Session.
```

So I suspect **that** might be the cause of some of the issues you are seeing in testing. To confirm, I would recommend:

- Create new instance of `DMEPullClient` before you do `authorize`
- If you have and old instance, it would be best to call `[dmePullClient cancel]` on it, so that it doesn;t continue data fetching in the background. (see https://github.com/digime/digime-sdk-ios/blob/master/DigiMeSDK/Core/Classes/DMEPullClient.h#L111)
- For now, use **either** `getSessionFileListWithUpdateHandler:completion:` **or** `getSessionDataWithDownloadHandler:completion:`
